# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FlashCardsUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#libs


#pyqt
from PyQt5 import QtCore, QtGui, QtWidgets

from Main import load_flashcard_set


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(649, 434)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 641, 391))
        self.tabWidget.setObjectName("tabWidget")
        self.progress_tab = QtWidgets.QWidget()
        self.progress_tab.setObjectName("progress_tab")
        self.label_3 = QtWidgets.QLabel(self.progress_tab)
        self.label_3.setGeometry(QtCore.QRect(70, 50, 251, 91))
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.progress_tab, "")
        self.flashcard_tab = QtWidgets.QWidget()
        self.flashcard_tab.setObjectName("flashcard_tab")
        self.label = QtWidgets.QLabel(self.flashcard_tab)
        self.label.setGeometry(QtCore.QRect(240, 100, 101, 31))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.flashcard_tab)
        self.line.setGeometry(QtCore.QRect(120, 160, 341, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.flashcard_tab)
        self.label_2.setGeometry(QtCore.QRect(250, 200, 121, 41))
        self.label_2.setObjectName("label_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.flashcard_tab)
        self.pushButton_5.setGeometry(QtCore.QRect(410, 320, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.flashcard_tab)
        self.pushButton_4.setGeometry(QtCore.QRect(280, 320, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.flashcard_tab)
        self.pushButton_3.setGeometry(QtCore.QRect(90, 320, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.flashcard_tab, "")
        self.flashcard_sets_tab = QtWidgets.QWidget()
        self.flashcard_sets_tab.setObjectName("flashcard_sets_tab")
        self.pushButton = QtWidgets.QPushButton(self.flashcard_sets_tab)
        self.pushButton.setGeometry(QtCore.QRect(240, 90, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.flashcard_sets_tab)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 130, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.scrollArea = QtWidgets.QScrollArea(self.flashcard_sets_tab)
        self.scrollArea.setGeometry(QtCore.QRect(10, 0, 171, 341))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 167, 337))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.FlashCard_Sets = QtWidgets.QListView(self.scrollAreaWidgetContents)
        self.FlashCard_Sets.setGeometry(QtCore.QRect(0, 0, 171, 321))
        self.FlashCard_Sets.setObjectName("FlashCard_Sets")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton_6 = QtWidgets.QPushButton(self.flashcard_sets_tab)
        self.pushButton_6.setGeometry(QtCore.QRect(240, 10, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit = QtWidgets.QLineEdit(self.flashcard_sets_tab)
        self.lineEdit.setGeometry(QtCore.QRect(360, 10, 251, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.flashcard_sets_tab)
        self.scrollArea_2.setGeometry(QtCore.QRect(360, 40, 251, 271))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 247, 267))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 10, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 10, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 251, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.pushButton_7 = QtWidgets.QPushButton(self.flashcard_sets_tab)
        self.pushButton_7.setGeometry(QtCore.QRect(360, 330, 101, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.flashcard_sets_tab)
        self.pushButton_8.setGeometry(QtCore.QRect(470, 330, 101, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.flashcard_sets_tab)
        self.pushButton_9.setGeometry(QtCore.QRect(570, 330, 51, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.flashcard_sets_tab)
        self.pushButton_10.setGeometry(QtCore.QRect(240, 50, 75, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.tabWidget.addTab(self.flashcard_sets_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 649, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Progres - not implemented"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.progress_tab), _translate("MainWindow", "Progress Tab"))
        self.label.setText(_translate("MainWindow", "Polish"))
        self.label_2.setText(_translate("MainWindow", "eanglish"))
        self.pushButton_5.setText(_translate("MainWindow", "Next"))
        self.pushButton_4.setText(_translate("MainWindow", "Check"))
        self.pushButton_3.setText(_translate("MainWindow", "I dont know"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.flashcard_tab), _translate("MainWindow", "Flashcards Tab"))
        self.pushButton.setText(_translate("MainWindow", "Add New"))
        self.pushButton_2.setText(_translate("MainWindow", "Delete Existing"))
        self.pushButton_6.setText(_translate("MainWindow", "Learn this set"))
        self.lineEdit.setText(_translate("MainWindow", "Name of set"))
        self.lineEdit_2.setText(_translate("MainWindow", "eanglish"))
        self.lineEdit_3.setText(_translate("MainWindow", "polish"))
        self.pushButton_7.setText(_translate("MainWindow", "add new flashcard"))
        self.pushButton_8.setText(_translate("MainWindow", "Delete Fleshcard"))
        self.pushButton_9.setText(_translate("MainWindow", "create"))
        self.pushButton_10.setText(_translate("MainWindow", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.flashcard_sets_tab), _translate("MainWindow", "Flashcard Sets Tab"))

        self.pushButton_10.clicked.connect(self.myfunc2)
        self.tabWidget.addTab
        #code


#### Functions form outside
def tak(self):
    self.flashcard_sets.add
Ui_MainWindow.myfunc = tak
####
Ui_MainWindow.myfunc2 = load_flashcard_set




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
